#!/bin/bash

#JAVA_HOME=`echo $JAVA_HOME`
APPLICATION_NAME=bankabc-integration-service-1.0.0
APPLICATION_PATH="$SCRIPT_DIR/$APPLICATION_NAME.jar"
PID_PATH="$SCRIPT_DIR/$APPLICATION_NAME.pid"
APPLICATION_PORT=8444
OUTPUT_PATH="$SCRIPT_DIR/$APPLICATION_NAME.out"